Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-062f7200baf2fa504 #Amazon Linux AMI
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - "Ec2 Instance for "
              - !Ref AWS::Region # Psuedo Parameter
      SecurityGroups:
        - !Ref sshSecurityGroup # Multiple resource 
  sshSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Enable port 22 to specific IP"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/24
