Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-1853ac65
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap: # Intrinsic function to use mappings
          - RegionMap  # Name of the mapping
          - !Ref AWS::Region # First Level Key, Psuedo parameter here to get the region name
          - AMI # Second Level Key in RegionMap mapping
      Tags:
        - Key: Name
          Value: !Join
            - ""
            - - "Ec2 Instance for "
              - !Ref AWS::Region # Psuedo Parameter
      SecurityGroups:
        - !Ref sshSecurityGroup # Multiple resource
  sshSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Enable port 22 to specific IP"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/24
